name: bookly
description: A new Flutter project.

publish_to: none # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  go_router: ^6.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.0.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  meta: ^1.8.0
  get_it: ^7.2.0
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  fancy_shimmer_image: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.12.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#100B20"
